name: Common Config

on:
  push:
    branches:
      - Dev
      - QA
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
    outputs:
      dev_var1:
        value: ${{ jobs.set_env_output.outputs.op_dev_var1 }}
      dev_var2:
        value: ${{ jobs.set_env_output.outputs.op_dev_var2 }}
      dev_var3:
        value: ${{ jobs.set_env_output.outputs.op_dev_var3 }}
      qa_var1:
        value: ${{ jobs.set_env_output.outputs.op_qa_var1 }}
      qa_var2:
        value: ${{ jobs.set_env_output.outputs.op_qa_var2 }}
      qa_var3:
        value: ${{ jobs.set_env_output.outputs.op_qa_var3 }}
      staging_var1:
        value: ${{ jobs.set_env_output.outputs.op_staging_var1 }}
      staging_var2:
        value: ${{ jobs.set_env_output.outputs.op_staging_var2 }}
      staging_var3:
        value: ${{ jobs.set_env_output.outputs.op_staging_var3 }}
jobs:
  set_env_output:
    runs-on: ubuntu-latest
    
    if: ${{ github.event_name == 'workflow_dispatch'}}
    outputs:
      op_dev_var1: ${{ steps.dev_vars.outputs.variable_a }}
      op_dev_var2: ${{ steps.dev_vars.outputs.variable_b }}
      op_dev_var3: ${{ steps.dev_vars.outputs.variable_c }}
      op_qa_var1: ${{ steps.qa_vars.outputs.variable_a }}
      op_qa_var2: ${{ steps.qa_vars.outputs.variable_b }}
      op_qa_var3: ${{ steps.qa_vars.outputs.variable_c }}
      op_staging_var1: ${{ steps.staging_vars.outputs.variable_a }}
      op_staging_var2: ${{ steps.staging_vars.outputs.variable_b }}
      op_staging_var3: ${{ steps.staging_vars.outputs.variable_c }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - id: dev_vars
        if: ${{ inputs.branch }} == "Dev"
        run: |
          echo "variable_a=Dev" >> $GITHUB_OUTPUT
          echo "variable_b=aDev" >> $GITHUB_OUTPUT
          echo "variable_c=bDev" >> $GITHUB_OUTPUT
          
      - id: qa_vars
        if: ${{ inputs.branch }} == "QA"
        run: |
          echo "variable_a=QA" >> $GITHUB_OUTPUT
          echo "variable_b=aQA" >> $GITHUB_OUTPUT
          echo "variable_c=bQA" >> $GITHUB_OUTPUT
          
      - id: staging_vars
        if: ${{ inputs.branch }} == "Staging"
        run: |
          echo "variable_a=Staging" >> $GITHUB_OUTPUT
          echo "variable_b=aStaging" >> $GITHUB_OUTPUT
          echo "variable_c=bStaging" >> $GITHUB_OUTPUT
          
      - name: Echo Variables
        run: |
          echo "variable_a: $variable_a"
          echo "variable_b: $variable_b"
          echo "variable_c: $variable_c"
