name: Common Config

on:
  push:
    branches:
      - dev
      - QA
  workflow_call:

jobs:
  check_branch:
    runs-on: ubuntu-latest
    
    if: ${{ github.event_name == 'workflow_dispatch'}}
    
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setting Dev variables
        if: github.ref == 'refs/heads/dev'
        run: |
          echo "variable_a=Dev" >> $GITHUB_ENV
          echo "variable_b=aDev" >> $GITHUB_ENV
          echo "variable_c=bDev" >> $GITHUB_ENV
      - name: Settiing QA variables
        if: github.ref == 'refs/heads/QA'
        run: |
          echo "variable_a=QA" >> $GITHUB_ENV
          echo "variable_b=aQA" >> $GITHUB_ENV
          echo "variable_c=bQA" >> $GITHUB_ENV
      - name: Echo Variables
        run: |
          echo "variable_a: $variable_a"
          echo "variable_b: $variable_b"
          echo "variable_c: $variable_c"
          
          
