name: Dev Deployment Workflow
on:
  push:
    branches:
      - "Dev"
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        required: true
        description: Select a branch to deploy
        options:
          - Dev

jobs:
  test:
    runs-on: ubuntu-latest
    
    if: ${{ github.event_name == 'workflow_dispatch' }}
    
    steps:
      - name: Print branch
        run: echo "dev"
