name: Dev Deployment Workflow
on:
  push:
    branches:
      - "Dev"
  workflow_dispatch:
    inputs:
      branch:
        description: 'Dev Branch'
        required: true
        default: 'Dev'
        type: string

jobs:

  Calling_common_config:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    uses: Suvit-Sharma/DevopsT/.github/workflows/cc.yaml@Dev
    
  Testing:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: git checkout 
        uses: actions/checkout@v3
        
      - name: cat Testing.txt(Dev)
        run: cat Testing.txt
