name: Dev Deployment Workflow
on:
  push:
    branches:
      - "Dev"
  workflow_dispatch:
    inputs:
      branch:
        description: 'Dev Branch'
        required: true
        default: 'Dev'
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    
    if: ${{ github.event_name == 'workflow_dispatch' }}
    
    steps:
      - name: Include Common Config Steps
        uses: ./.github/workflows/cc.yaml
        
      - name: git checkout 
        uses: actions/checkout@v3
        
      - name: cat Testing.txt(Dev)
        run: cat Testing.txt
