name: test workflow
on:
 workflow_dispatch:
   inputs:
     choice:
       type: choice
       required: true
       description: Select a branch to deploy
       options:
       - Dev
       - QA
       - Staging
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print branch
        run: |
          if [ "${{ inputs.choice }}" == "Dev" ]; then
            echo "dev"
          elif [ "${{ inputs.choice }}" == "QA" ]; then
            echo "qa"
          elif [ "${{ inputs.choice }}" == "Staging" ]; then
            echo "staging"
          else
            echo "Invalid choice"
          fi

