name: Master Deployment Workflow
on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        required: true
        description: Select a branch to deploy
        options:
          - Dev
          - QA
          - Staging

jobs:
  execute_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List branches
        run: git branch -a

      - name: Execute workflow for selected branch
        run: |
          if [ "${{ inputs.choice }}" == "Dev" ]; then
            echo "Executing workflow for Dev branch"
            git fetch --all
            git branch -a
            git checkout Dev
          elif [ "${{ inputs.choice }}" == "QA" ]; then
            echo "Executing workflow for QA branch"
            git fetch --all
            git branch -a
            git checkout QA
          elif [ "${{ inputs.choice }}" == "Staging" ]; then
            echo "Executing workflow for Staging branch"
            git fetch --all
            git branch -a
            git checkout Staging
          else
            echo "Invalid choice"
            exit 1
          fi
          # Create a new workflow run on the current branch
          echo "Running workflow on the selected branch: ${{ github.ref }}"
          echo "Branch name: ${{ github.head_ref }}"
          echo "SHA: ${{ github.sha }}"
          gh workflow run --ref "${{ github.ref }}"
