name: Master Deployment Workflow
on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        required: true
        description: Select a branch to deploy
        options:
          - Dev
          - QA
          - Staging

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  execute_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List branches
        run: git branch -a

      - name: Execute workflow for selected branch
        run: |
          if [ "${{ inputs.choice }}" == "Dev" ]; then
            echo "Executing workflow for Dev branch"
            git fetch --all
            git branch -a
            git checkout Dev
            echo "Running workflow on the Dev branch..."
            workflow_file="Dev.yaml"
          elif [ "${{ inputs.choice }}" == "QA" ]; then
            echo "Executing workflow for QA branch"
            git fetch --all
            git branch -a
            git checkout QA
            echo "Running workflow on the QA branch..."
            workflow_file="QA.yaml"
          elif [ "${{ inputs.choice }}" == "Staging" ]; then
            echo "Executing workflow for Staging branch"
            git fetch --all
            git branch -a
            git checkout Staging
            echo "Running workflow on the Staging branch..."
            workflow_file="Staging.yaml"
          else
            echo "Invalid choice"
            exit 1
          fi

          # Trigger the workflow run using GitHub's REST API
          curl -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/Suvit-Sharma/DevopsT/actions/workflows/$workflow_file/dispatches" \
            -d '{"ref": "'${{ github.ref }}'", "inputs": {}}'
