name: test workflow
on:
 workflow_dispatch:
   inputs:
     branch:
       description: 'Branch to deploy'
       required: true
       default: 'Dev, QA, Staging'
     choice:
       type: choice
       description: Select a branch 
       options:
       - Dev
       - QA
       - Staging
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2       
