name: test workflow
on:
 workflow_dispatch:
   inputs:
     choice:
       type: choice
       required: true
       description: Select a branch to deploy
       options:
       - Dev
       - QA
       - Staging
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2       
