name: test workflow
on:
 pull_request:
   types:
     - closed
 workflow_dispatch:
   inputs:
     branch:
       description: 'Branch to deploy'
       required: true
       default: 'Dev, QA, Staging'

