name: Master Deployment Workflow
on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        required: true
        description: Select a branch to deploy
        options:
          - Dev
          - QA
          - Staging

jobs:
  execute_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Execute workflow for selected branch
        run: |
          if [ "${{ inputs.choice }}" == "Dev" ]; then
            echo "Executing workflow for Dev branch"
            git checkout dev
          elif [ "${{ inputs.choice }}" == "QA" ]; then
            echo "Executing workflow for QA branch"
            git checkout qa
          elif [ "${{ inputs.choice }}" == "Staging" ]; then
            echo "Executing workflow for Staging branch"
            git checkout staging
          else
            echo "Invalid choice"
            exit 1
          fi
          gh workflow run

