name: Master Deployment Workflow
on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        required: true
        description: Select a branch to deploy
        options:
          - Dev
          - QA
          - Staging

jobs:
  execute_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List branches
        run: git branch -a

      - name: Execute workflow for selected branch
        run: |
          if [ "${{ inputs.choice }}" == "Dev" ]; then
            echo "Executing workflow for Dev branch"
            git fetch --all
            git branch -a
            git checkout Dev
            echo "Running workflow on the Dev branch..."
            gh repo clone Suvit-Sharma/DevopsT temp-repo
            cd temp-repo
            git checkout Dev
            gh workflow run Dev.yaml
          elif [ "${{ inputs.choice }}" == "QA" ]; then
            echo "Executing workflow for QA branch"
            git fetch --all
            git branch -a
            git checkout QA
            echo "Running workflow on the QA branch..."
            gh repo clone Suvit-Sharma/DevopsT temp-repo
            cd temp-repo
            git checkout QA
            gh workflow run QA.yaml
          elif [ "${{ inputs.choice }}" == "Staging" ]; then
            echo "Executing workflow for Staging branch"
            git fetch --all
            git branch -a
            git checkout Staging
            echo "Running workflow on the Staging branch..."
            gh repo clone Suvit-Sharma/DevopsT temp-repo
            cd temp-repo
            git checkout Staging
            gh workflow run Staging.yaml
          else
            echo "Invalid choice"
            exit 1
          fi
