name: Staging Deployment Workflow
on:
  push:
    branches:
      - "Staging"
  workflow_dispatch:
    inputs:
      branch:
        description: 'Staging Branch'
        required: true
        default: 'Staging'
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    
    if: ${{ github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Print branch
        run: echo "staging"
