name: Staging Deployment Workflow
on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        required: true
        description: Select a branch to deploy
        options:
          - Staging

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print branch
        run: echo "staging"
