name: QA Deployment Workflow
on:
  push:
    branches:
      - "TestQA"
  workflow_dispatch:
    inputs:
      branch:
        description: 'QA Branch'
        required: true
        default: 'QA'
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    
    if: ${{ github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Print branch
        run: echo "QA"
